version: '2'

services:
  webgoat:
    build:
      context: .
      dockerfile: Dockerfile
    image: ecstatic-nobel/webgoat-n-docker:openjdk-8-jre
    labels:
      - webgoat-n-docker
    ports:
      - '8080:8080'
    restart: always
    tty: true
  webgoat_armhf:
    build:
      context: .
      dockerfile: Dockerfile-Armhf
    image: ecstatic-nobel/webgoat-n-docker:openjdk-8-jre
    labels:
      - webgoat-n-docker
    ports:
      - '8080:8080'
    restart: always
    tty: true
